---
# tasks file for ansible-role-acas
- name: Validate no web servers are installed
  ansible.builtin.dnf: 
    name:
      - httpd
      - nginx
    state: absent
    autoremove: true
# Set Timezone to UTC
# Install pre-requisite software
- name: Install pre-requisite software
  ansible.builtin.dnf:
    name:
      - zip
      - unzip
      - expat
      - sed
      - rsync
      - libxslt
      - libxml2
      - dialog
      - opensc
      - bc
      - aide
      - logwatch
      - chrony
      - postfix
      - python2
      - nss-tools
      - pcsc-lite
      - fapolicyd
      - tmux
      - esc 
      - openssl-pkcs11
      - usbguard
      - rng-tools
      - python3-pexpect
      - sqlite
    state: present
# 3.3.1. Reconfigure Mount Points to use STIG Required Mount Options
- name: /boot mount options
  ansible.builtin.shell: sed -r -i 's|(/boot\s.*defaults)\s|\1,nodev,nosuid |' /etc/fstab
- name: /tmp mount options
  ansible.builtin.shell: sed -r -i 's|(/tmp\s.*defaults)\s|\1,nodev,noexec,nosuid |' /etc/fstab
- name: /home mount options
  ansible.builtin.shell: sed -r -i 's|(/home\s.*defaults)\s|\1,nodev,noexec,nosuid |' /etc/fstab
- name: /var mount options
  ansible.builtin.shell: sed -r -i 's|(/var\s.*defaults)\s|\1,nodev |' /etc/fstab
- name: /var/log mount options
  ansible.builtin.shell: sed -r -i 's|(/var/log\s.*defaults)\s|\1,nodev,noexec,nosuid |' /etc/fstab
- name: /var/log/audit mount options
  ansible.builtin.shell: sed -r -i 's|(/var/log/audit\s.*defaults)\s|\1,nodev,noexec,nosuid |' /etc/fstab
# This step is failing...need to troubleshoot
# - name: /boot/efi mount options
#   ansible.builtin.shell: sed -r -i 's|(/boot/efi\s.*umask=0077,shortname=winnt\s|1,nosuid |' /etc/fstab
# 3.3.2. Reconfigure the Volume Group to Accommodate ACAS-specified Partitions
- name: Determine last partition number
  community.general.parted:
    device: /dev/sdb
    state: info
  register: sda_info
- name: Create the /dev/sdb1 partition
  community.general.parted:
    device: /dev/sdb
    number: 1
    label: gpt
    part_end: "100%"
    state: present
- name: Add /dev/sdb1 to the the Logical Volume Group
  community.general.lvg:
    vg: sysvg
    pvs:
      - /dev/sda3
      - /dev/sdb1
    pvresize: true
    state: present
- name: Unmount the /opt partition
  ansible.posix.mount:
    path: /opt
    state: unmounted
- name: Modify Logical Volume for /opt
  community.general.lvol:
    vg: 'sysvg'
    lv: 'lv_opt'
    size: 500g
    resizefs: true
- name: Modify Logical Volume for /opt/sc/www
  community.general.lvol:
    vg: 'sysvg'
    lv: 'lv_tenable_www'
    size: 5g
    state: present
- name: Modify Logical Volume for /opt/nessus/var/nessus/www
  community.general.lvol:
    vg: 'sysvg'
    lv: 'lv_nessus_www'
    size: 5g
    state: present
- name: Format the Tenable.sc www logical Volume
  community.general.filesystem:
    fstype: xfs
    dev: /dev/mapper/sysvg-lv_tenable_www
    state: present
- name: Format the Nessus www logical Volume
  community.general.filesystem:
    fstype: xfs
    dev: /dev/mapper/sysvg-lv_nessus_www
    state: present
- name: Mount the opt partition
  ansible.posix.mount:
    path: /opt
    src: /dev/mapper/sysvg-lv_opt
    opts: defaults,nodev,nosuid
    fstype: xfs
    state: mounted
- name: Mount the Tenable.sc www partition
  ansible.posix.mount:
    path: /opt/sc/www
    src: /dev/mapper/sysvg-lv_tenable_www
    opts: defaults,nodev,nosuid
    fstype: xfs
    state: mounted
- name: Mount the Nessus www partition
  ansible.posix.mount:
    path: /opt/nessus/var/nessus/www
    src: /dev/mapper/sysvg-lv_nessus_www
    opts: defaults,nodev,nosuid
    fstype: xfs
    state: mounted
# 3.3.3. Create the PAM faillock Directory and Set SE Linux Context
- name: Create PAM faillock directory
  ansible.builtin.file:
    path: /var/log/faillock
    state: directory
- name: Set SELinux Context
  community.general.sefcontext:
    ftype: 'a'
    target: '/var/log/faillock(/.*)?'
    setype: faillog_t
    state: present
- name: Restore faillock SEContext 
  ansible.builtin.command: restorecon -R /var/log/faillock
# 3.3.5. Install Updated Audit Daemon Rules File for STIG Compliance
- name: Install Updated Audit Daemon Rules
  ansible.builtin.copy:
    src: CM-290131_RH8audit.rules
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0644'
  notify:
    - do_reboot
# Enable FIPS Mode
- name: Enable FIPS mode
  command: /usr/bin/fips-mode-setup --enable
- name: Enable Dracut FIPS Module
  lineinfile:
    path: /etc/dracut.conf.d/40-fips.conf
    line: add_dracutmodules+=" fips "
- name: Enable FIPS Mode
  lineinfile:
    path: /etc/crypto-policies/config
    regexp: ^(?!#)(\S+)$
    line: '{{ var_system_crypto_policy }}'
    create: true
- name: 'Configure GnuTLS library to use DoD-approved TLS Encryption: set_fact'
  set_fact:
    path: /etc/crypto-policies/back-ends/gnutls.config
    correct_value: +VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0
    lineinfile_reg: \+VERS-ALL:-VERS-DTLS0\.9:-VERS-SSL3\.0:-VERS-TLS1\.0:-VERS-TLS1\.1:-VERS-DTLS1\.0
# 3.3.6. Configure RHEL 8 system per Site Responsibility STIGs’
- name: Enable fapolicyd Service
  ansible.builtin.service:
    name: fapolicyd.service 
    enabled: true
  notify:
    - Restartfapolicyd
- name: Enable USBGuard Service 
  ansible.builtin.service:
    name: usbguard.service
    enabled: true
  notify:
    - RestartUSBGuard
- name: Set GRUB Password 
  ansible.builtin.expect:
    command: grub2-mkpasswd-pbkdf2
    responses:
      Enter password: '{{ grub2_password }}'
      Reenter password: '{{ grub2_password }}'
  no_log: true
- name: Install acas-configure package
  ansible.builtin.dnf:
    name: '{{ acas_configure_url }}'
    disable_gpg_check: true
    sslverify: '{{ verify_repository_ssl }}'
    state: present
- name: Install Tenable RPM Key
  ansible.builtin.rpm_key:
    key: /opt/acas/var/RPM-GPG-KEY-Tenable
    state: present
